default_language_version:
  python: python3.11
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
      - id: detect-private-key
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args:
          - --py38-plus
  - repo: https://github.com/pycqa/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
          - --ignore-init-module-imports
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
  - repo: https://github.com/adamchainz/blacken-docs
    rev: 1.16.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==23.9.1]
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-tidy-imports
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.27.0
    hooks:
      - id: check-github-workflows
# - repo: https://github.com/mgedmin/check-manifest
#   rev: "0.47"
#   hooks:
#     - id: check-manifest
#       # See https://github.com/mgedmin/check-manifest/issues/141
#       args: ["--no-build-isolation"]
# Unsure how to solve this failing

exclude: |
  (?x)(
    /(
      \.eggs
      | \.git
      | \.hg
      | \.mypy_cache
      | \.pytest_cache
      | \.nox
      | \.tox
      | \.venv
      | _build
      | buck-out
      | build
      | dist
    )/
    | ^(
      example
      | scripts
      | tests/project/files
    )/
  )
