default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.3.0"
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
      - id: detect-private-key
  - repo: https://github.com/asottile/pyupgrade
    rev: "v2.37.3"
    hooks:
      - id: pyupgrade
        args:
          - --py37-plus
  - repo: https://github.com/myint/autoflake
    rev: "v1.5.1"
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
          - --ignore-init-module-imports
  - repo: https://github.com/pycqa/isort
    rev: "5.12.0"
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: "22.6.0"
    hooks:
      - id: black
  - repo: https://github.com/asottile/blacken-docs
    rev: "v1.12.1"
    hooks:
      - id: blacken-docs
        additional_dependencies: ["black==22.6.0"]
  - repo: https://github.com/pycqa/flake8
    rev: "5.0.4"
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-tidy-imports
          - flake8-print
  - repo: https://github.com/sirosen/check-jsonschema
    rev: "0.18.1"
    hooks:
      - id: check-github-workflows
  - repo: https://github.com/mgedmin/check-manifest
    rev: "0.48"
    hooks:
      - id: check-manifest
        # See https://github.com/mgedmin/check-manifest/issues/141
        args: ["--no-build-isolation"]

exclude: |
  (?x)(
    /(
      \.eggs
      | \.git
      | \.hg
      | \.mypy_cache
      | \.pytest_cache
      | \.nox
      | \.tox
      | \.venv
      | _build
      | buck-out
      | build
      | dist
    )/
    | ^(
      example
      | scripts
      | tests/project/files
    )/
  )
