version: "3.3"

services:
  django:
    build: .
    command: ["runserver", "0.0.0.0:8000"]
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - .:/djedi-cms
      - media-files:/media
    environment:
      - DJEDI_THEME=${DJEDI_THEME:-}

  node:
    build: ./djedi-react
    command: ["npm", "start"]
    ports:
      - "3000:3000"
    volumes:
      - ./djedi-react/:/code
      - /code/node_modules
    environment:
      - DJEDI_REACT_DIR=${DJEDI_REACT_DIR:-}
      - SERVER_BASE_URL=http://django:8000/djedi/api

  # Piggy-backing on djedi-react’s image and node_modules to watch CoffeeScript
  # and Less files.
  coffee:
    build: ./djedi-react
    command: ["make", "coffee", "ARGS=--watch"]
    volumes:
      - .:/code
      - /code/node_modules
  less:
    build: ./djedi-react
    command:
      [
        "onchange",
        "--initial",
        "djedi/static/djedi/themes/**/*.less",
        "--",
        "make",
        "less",
        "--silent",
      ]
    volumes:
      - .:/code
      - /code/node_modules

volumes:
  media-files:
