version: "3.3"

services:
  django:
    build: .
    command: ["runserver", "0.0.0.0:8000"]
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - .:/djedi-cms

  node:
    build: ./djedi-react
    image: djedi-react
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./djedi-react/:/code
      - /code/node_modules
