# Generated by Django 4.2.6 on 2023-10-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djedi", "0002_auto_20190722_1447"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
