version: 2

steps: &steps
  steps:
    - checkout
    - run: {command: sudo pip install tox}
    - run: {command: tox}
    - persist_to_workspace:
        root: .
        paths:
          - .coverage.*

jobs:
  py36:
    docker: [{image: 'circleci/python:3.6'}]
    environment: {TOXENV: 'py36-django{111,20}'}
    <<: *steps

  py35:
    docker: [{image: 'circleci/python:3.5'}]
    environment: {TOXENV: 'py35-django{18,19,110,111,20}'}
    <<: *steps

  py34:
    docker: [{image: 'circleci/python:3.4'}]
    environment: {TOXENV: 'py34-django{17,18,19,110,111,20}'}
    <<: *steps

  py27:
    docker: [{image: 'circleci/python:2.7'}]
    environment: {TOXENV: 'py27-django{15,16,17,18,19,110,111}'}
    <<: *steps

  coverage:
    docker: [{image: 'circleci/python:3.5'}]
    steps:
      - checkout
      - attach_workspace: {at: .}
      - run: {command: sudo pip install coverage}
      - run: {command: make coverage}
      - run: {command: sudo pip install python-coveralls}
      - run: {command: coveralls}

workflows:
  version: 2
  tests-and-coverage:
    jobs:
      - py27
      - py34
      - py35
      - py36
      - coverage:
          requires:
            - py27
            - py34
            - py35
            - py36
