name: Release djedi-react

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'djedi-react/package-json'

jobs:
  release:
    name: Build and push npm release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        working-directory: ./djedi-react
        run: npm ci
      - name: Build package
        working-directory: ./djedi-react
        run: npm run build
      - name: Publish package
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./djedi-react/package.json
